import * as db from '../db.js';
import { qs, escapeHtml } from '../ui.js';
import { practiceFocus } from '../roundAnalysis.js';

// Next Practice — docs/course-mode-spec.md §4.6, Reference E.
//
// PARTIAL: the focus and plan shown here are real, generated by
// roundAnalysis.js's practiceFocus() from this round's own holes. What is
// NOT built yet is the plan LIFECYCLE from §7 — saving a plan, the
// practice_plans store and its statuses, and starting a saved plan as a
// range session. That is the next phase, and until it exists this screen
// deliberately offers no Save button rather than a button that quietly does
// nothing.
//
// The focus block is not wrapped in a card on purpose (§4.6): it is the
// screen's subject, not one item among several.

export function renderPracticePlan(root, roundId) {
  const round = db.getRound(roundId);
  if (!round) { location.hash = '#/history'; return; }

  const holes = db.getHolesForRound(roundId);
  const focus = practiceFocus(round, holes);
  if (!focus) { location.hash = `#/course/summary/${roundId}`; return; }

  root.innerHTML = `
    <div class="screen">
      <div class="course-hero compact">
        <img class="course-hero-img" src="graphics/home/range_hero.webp" alt="" />
        <div class="course-hero-scrim"></div>
        <div class="topbar course-hero-topbar">
          <button class="back" id="backBtn">&larr; Back</button>
          <span class="side-space"></span>
        </div>
      </div>

      <div class="scroll">
        <div class="focus-block">
          <div class="focus-eyebrow">Focus for next time</div>
          <div class="focus-title">${escapeHtml(focus.focus_title)}</div>
          <div class="focus-rationale">${escapeHtml(focus.focus_rationale)}</div>
          <div class="focus-goal">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="12" r="8.2" /><circle cx="12" cy="12" r="4.6" /><circle cx="12" cy="12" r="1.1" fill="currentColor" /></svg>
            <span><b>Goal:</b> ${escapeHtml(focus.goal_text)}</span>
          </div>
        </div>

        <div class="card">
          <div class="card-eyebrow">Your Practice Plan</div>
          <div class="plan-steps">
            ${focus.steps.map((s) => `
              <div class="plan-step">
                <span class="plan-step-num">${s.order}</span>
                <span class="plan-step-text">
                  <span class="plan-step-title">${escapeHtml(s.title)}</span>
                  <span class="plan-step-detail">${escapeHtml(s.detail)}</span>
                </span>
              </div>`).join('')}
          </div>
        </div>

        <p class="tiny muted" style="margin-top:var(--space-5);">Saving this plan &mdash; and starting it as a range session &mdash; arrives in the next step.</p>
      </div>

      <button class="btn btn-primary btn-hero" id="doneBtn">Done</button>
    </div>
  `;

  qs('#backBtn', root).addEventListener('click', () => { location.hash = `#/course/summary/${roundId}`; });
  qs('#doneBtn', root).addEventListener('click', () => { location.hash = '#/home'; });
}
